export default{
  state: {
    allproducts : {
      product : [
      { categories : 'POS for Restaurant',
        explanation : 'POS software for Restaurant', 
        mainItemPrice : 649.00,  
        mainItemImg : 'https://kimjihwan0618.github.io/project/Web/h.wave/item1.png',
        prouducts : [
          { name : 'POS for Restaurant Product1',
            explanation : 'POS for Restaurant Product text1',
            price: 549.00,
            sale : 649.00,
            img: 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item1/item1-1.jpg',
            percent : 30,
            count : 1,
            subImg : [
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item1/item1-1.jpg' },    
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item1/item1-1/item1-1-2.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item1/item1-1/item1-1-3.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item1/item1-1/item1-1-4.png' },  
            ]
          },      
          { name : 'POS for Restaurant Product2', 
            explanation : 'POS for Restaurant Product text2', 
            price: 349.00, 
            sale : 629.00, 
            img: 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item1/item1-2.jpg', 
            percent : 30,
            count : 1,
            subImg : [
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item1/item1-2.jpg' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item1/item1-2/item1-2-2.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item1/item1-2/item1-2-3.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item1/item1-2/item1-2-4.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item1/item1-2/item1-2-5.png' },  
            ]
          },      
          { name : 'POS for Restaurant Product3', 
            explanation : 'POS for Restaurant Product text3', 
            price: 559.00, 
            sale : 579.00, 
            img: 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item1/item1-3.jpg', 
            percent : 30,
            count : 1,
            subImg : [
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item1/item1-3.jpg' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item1/item1-3/item1-3-2.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item1/item1-3/item1-3-3.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item1/item1-3/item1-3-4.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item1/item1-3/item1-3-5.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item1/item1-3/item1-3-6.png' },  
            ]
          },
          { name : 'POS for Restaurant Product4', 
            explanation : 'POS for Restaurant Product text4', 
            price: 409.00, sale : 519.00, 
            img: 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item1/item1-4.jpg', 
            percent : 30,
            count : 1,
            subImg : [  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item1/item1-4.jpg' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item1/item1-4/item1-4-2.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item1/item1-4/item1-4-3.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item1/item1-4/item1-4-4.png' },  
            ]
          }
        ]
      },
      { categories : 'POS for Minimart',
        explanation : 'POS Hardware for Minimart',
        mainItemPrice : 359.00,
        mainItemImg : 'https://kimjihwan0618.github.io/project/Web/h.wave/item2.png',
        prouducts : [
          { name : 'POS for Minimart Product1', 
            explanation : 'POS for Minimart Product text1', 
            price: 400.00, 
            sale : 501.00, 
            img: 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item2/item2-1.jpg', 
            percent : 30,
            count : 1,
            subImg : [
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item2/item2-1.jpg' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item2/item2-1/item2-1-2.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item2/item2-1/item2-1-3.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item2/item2-1/item2-1-4.png' }
            ]
          },
          { name : 'POS for Minimart Product2', 
            explanation : 'POS for Minimart Product text2', 
            price: 380.00, 
            sale : 489.00, 
            img: 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item2/item2-2.jpg', 
            percent : 30,
            count : 1,
            subImg : [
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item2/item2-2.jpg' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item2/item2-2/item2-2-2.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item2/item2-2/item2-2-3.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item2/item2-2/item2-2-4.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item2/item2-2/item2-2-5.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item2/item2-2/item2-2-6.png' }, 
            ]
          },
          { name : 'POS for Minimart Product3', 
            explanation : 'POS for Minimart Product text3', 
            price: 409.00, 
            sale : 429.00, 
            img: 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item2/item2-3.jpg', 
            percent : 30,
            count : 1,
            subImg : [
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item2/item2-3.jpg' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item2/item2-3/item2-3-2.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item2/item2-3/item2-3-3.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item2/item2-3/item2-3-4.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item2/item2-3/item2-3-5.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item2/item2-3/item2-3-6.png' }, 
            ]
          },
        ]
      },
      { categories : 'h.STORE',
        explanation : 'h.Store explanation',
        mainItemPrice : 459.00,
        mainItemImg : 'https://kimjihwan0618.github.io/project/Web/h.wave/item3.jpg',
        prouducts : [
          { name : 'h.STORE Product1',
            explanation : 'h.STORE Product text1', 
            price: 559.00, 
            sale : 559.00, 
            img: 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item3/item3-1.jpg', 
            percent : 30,
            count : 1,
              subImg : [
                { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item3/item3-1.jpg' },  
                { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item3/item3-1/item3-1-2.png' },  
                { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item3/item3-1/item3-1-3.png' },  
                { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item3/item3-1/item3-1-4.png' },  
                { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item3/item3-1/item3-1-5.png' },  
                { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item3/item3-1/item3-1-6.png' },  
              ]
          },
          { name : 'h.STORE Product2', 
            explanation : 'h.STORE Product text2', 
            price: 559.00, 
            sale : 559.00, 
            img: 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item3/item3-2.jpg', 
            percent : 30,
            count : 1,
            subImg : [
              { subImg5 : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item3/item3-2.jpg' },  
              { subImg6 : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item3/item3-2/item3-2-2.png' },  
            ]
          },
          { name : 'h.STORE Product3', 
            explanation : 'h.STORE Product text3', 
            price: 559.00, 
            sale : 559.00, 
            img: 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item3/item3-3.png', 
            percent : 30,
            count : 1,
            subImg : [
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item3/item3-3.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item3/item3-3/item3-3-2.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item3/item3-3/item3-3-3.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item3/item3-3/item3-3-4.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item3/item3-3/item3-3-5.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item3/item3-3/item3-3-6.png' },  
            ]
          },
          { name : 'h.STORE Product4',
            explanation : 'h.STORE Product text4', 
            price: 559.00, 
            sale : 559.00, 
            img: 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item3/item3-4.png', 
            percent : 30,
            count : 1,
            subImg : [
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item3/item3-4.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item3/item3-4/item3-4-2.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item3/item3-4/item3-4-3.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item3/item3-4/item3-4-4.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item3/item3-4/item3-4-5.png' },  
            ]
          },
          { name : 'h.STORE Product5', 
            explanation : 'h.STORE Product text5', 
            price: 559.00, 
            sale : 559.00, 
            img: 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item3/item3-5.jpg', 
            percent : 30,
            count : 1,
            subImg : [
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item3/item3-5.jpg' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item3/item3-5/item3-5-2.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item3/item3-5/item3-5-3.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item3/item3-5/item3-5-4.png' }, 
            ]
          }
        ]
      },
      { categories : 'h.ORDER',
        explanation : 'h.ORDER explanation',
        mainItemPrice : 759.00,
        mainItemImg : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4.png',
        prouducts : [
          { name : 'h.ORDER Product1', 
            explanation : 'h,ORDER Product text1', 
            price: 559.00, 
            ale : 559.00, 
            img: 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-1.jpg', 
            percent : 30,
            count : 1,
            subImg : [
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-1.jpg' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-1/item4-1-2.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-1/item4-1-3.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-1/item4-1-4.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-1/item4-1-5.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-1/item4-1-6.png' }, 
            ]
          },
          { name : 'h.ORDER Product2',
            explanation : 'h,ORDER Product text2', 
            price: 559.00, 
            sale : 559.00, 
            img: 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-2.jpg', 
            percent : 30,
            count : 1,
            subImg : [
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-2.jpg' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-2/item4-2-2.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-2/item4-2-3.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-2/item4-2-4.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-2/item4-2-5.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-2/item4-2-6.png' },  
            ]
          },
          { name : 'h.ORDER Product3', 
            explanation : 'h,ORDER Product text3', 
            price: 559.00, 
            sale : 559.00, 
            img: 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-3.jpg', 
            percent : 30,
            count : 1,
            subImg : [
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-3.jpg' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-3/item4-3-2.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-3/item4-3-3.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-3/item4-3-4.png' }
            ]
          },
          { name : 'h.ORDER Product4', 
            explanation : 'h,ORDER Product text4', 
            price: 559.00, 
            sale : 559.00, 
            img: 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-4.jpg', 
            percent : 30,
            count : 1,
            subImg : [
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-4.jpg' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-4/item4-4-2.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-4/item4-4-3.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-4/item4-4-4.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-4/item4-4-5.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-4/item4-4-6.png' }, 
            ]
          },
          { name : 'h.ORDER Product5', 
            explanation : 'h,ORDER Product text5', 
            price: 559.00, 
            sale : 559.00, 
            img: 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-5.jpg', 
            percent : 30,
            count : 1,
            subImg : [
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-5.jpg' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-5/item4-5-2.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-5/item4-5-3.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-5/item4-5-4.png' }, 
            ]    
          },
          { name : 'h.ORDER Product6', 
            explanation : 'h,ORDER Product text6',
            price: 559.00, 
            sale : 559.00, 
            img: 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-6.jpg', 
            percent : 30,
            count : 1,
            subImg : [
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-6.jpg' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-6/item4-6-2.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-6/item4-6-3.png' },  
              { imgList : 'https://kimjihwan0618.github.io/project/Web/h.wave/item/item4/item4-6/item4-6-4.png' },  
            ]
          }
        ]
      }]
    }
  }
}